// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DetailedCharge() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col mt-8\"><!-- Subtotal --><div class=\"flex justify-between\"><div class=\"self-center font-medium tracking-tight text-slate-600\">SUBTOTAL</div><div class=\"text-right text-lg\">$227,315.00</div></div><!-- Divider --><div class=\"col-span-12 my-3 border-b\"></div><!-- Tax --><div class=\"flex justify-between\"><div class=\"self-center font-medium tracking-tight text-slate-600\">IMPUESTOS</div><div class=\"col-span-2 text-right text-lg\">$11,365.75</div></div><!-- Divider --><div class=\"col-span-12 my-3 border-b\"></div><!-- Discount --><div class=\"flex justify-between\"><div class=\"col-span-10 self-center font-medium tracking-tight text-slate-600\">DESCUENTO</div><div class=\"col-span-2 text-right text-lg\">$3,680.75</div></div><!-- Divider --><div class=\"col-span-12 my-3 border-b\"></div><!-- Total --><div class=\"flex justify-between\"><div class=\"col-span-10 self-center text-2xl font-medium tracking-tight text-slate-600\">TOTAL</div><div class=\"col-span-2 text-right text-2xl font-medium\">$235,000.00</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
