// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ServicesTable() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-12 gap-x-1 mt-8\"><!-- Columns --><div class=\"col-span-8 font-medium text-md text-slate-600\">SERVICIO</div><div class=\"font-medium text-md text-right text-slate-600\">TASA</div><div class=\"font-medium text-md text-right text-slate-600\">QTY</div><div class=\"col-span-2 font-medium text-md text-right text-slate-600\">TOTAL</div><!-- Divider --><div class=\"col-span-12 my-2 border-b\"></div><!-- Item --><div class=\"col-span-8 text-lg font-medium\">Prototype & Design</div><div class=\"self-center text-right\">$75.00</div><div class=\"self-center text-right\">240</div><div class=\"col-span-2 self-center text-right\">$18,000.00</div><!-- Divider --><div class=\"col-span-12 my-2 border-b\"></div><!-- Item --><div class=\"col-span-8 text-lg font-medium\">Development</div><div class=\"self-center text-right\">$60.50</div><div class=\"self-center text-right\">350</div><div class=\"col-span-2 self-center text-right\">$21,175.00</div><!-- Divider --><div class=\"col-span-12 my-2 border-b\"></div><!-- Item --><div class=\"col-span-8 text-lg font-medium\">Testing</div><div class=\"self-center text-right\">$25.00</div><div class=\"self-center text-right\">50</div><div class=\"col-span-2 self-center text-right\">$1,250.00</div><!-- Divider --><div class=\"col-span-12 my-2 border-b\"></div><!-- Item --><div class=\"col-span-8 text-lg font-medium\">Documentation & Training</div><div class=\"self-center text-right\">$26.50</div><div class=\"self-center text-right\">260</div><div class=\"col-span-2 self-center text-right\">$6,890.00</div><!-- Divider --><div class=\"col-span-12 my-2 border-b\"></div><!-- Item --><div class=\"col-span-8 text-lg font-medium\">Critical bug fixes for a year</div><div class=\"self-center text-right\">$25,000</div><div class=\"self-center text-right\">2</div><div class=\"col-span-2 self-center text-right\">$50,000.00</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
